### ISSUE TITLE
Error with all test classes wildcard

### ISSUE THREAD

**Issue by 13Rise** [forcedotcom/ApexUnit#12] opened 2015-11-23 20:02 UTC
One more question is it possible to run all apex testclasses and get an report for all apex classes ?
maybe it would be better to switch to an SOSL Query for dynamic getting all Testclasses
FIND {@IsTest} IN ALL FIELDS RETURNING ApexClass

It tried this with some errors:
-regex.for.selecting.test.classes.to.execute *
-regex.for.selecting.source.classes.for.code.coverage.computation *

[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.utils.ApexClassFetcherUtils - Using regex(es): * to fetch apex classes
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.utils.ApexClassFetcherUtils - Using regex: "*" to fetch apex classes
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.connection.ConnectionHandler - Bulk connection established.
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.testEngine.AsyncBulkApiHandler - Creating batch for the test classes to execute using bulk connection....
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] ERROR com.sforce.cd.apexUnit.ApexUnitUtils - Error while fetching results for the batch jobFIELD_INTEGRITY_EXCEPTION:Class ID: id value of incorrect type: 01qD0000000Q8vZIAS:ApexClassId --
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.ApexUnitUtils - Shutting down ApexUnit
java.lang.Exception: Stack trace
        at java.lang.Thread.dumpStack(Thread.java:1365)
        at com.sforce.cd.apexUnit.ApexUnitUtils.shutDownWithErrMsg(ApexUnitUtils.java:68)
        at com.sforce.cd.apexUnit.client.testEngine.AsyncBulkApiHandler.checkResults(AsyncBulkApiHandler.java:295)
        at com.sforce.cd.apexUnit.client.testEngine.AsyncBulkApiHandler.handleBulkApiFlow(AsyncBulkApiHandler.java:100)
        at com.sforce.cd.apexUnit.client.testEngine.TestExecutor.testExecutionFlow(TestExecutor.java:61)
        at com.sforce.cd.apexUnit.ApexUnitRunner.main(ApexUnitRunner.java:93)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
        at java.lang.Thread.run(Thread.java:745)

**Comment by 13Rise** [comment] 2015-12-08 23:00
we want to use your tool for our continuous integration process.
In this process we want to run testdeployments, realdeployments, static code analysis with Sonar Qube and testclass runs with code coverage report.
Our missing part is only the testclass execution with code coverage report.

On the customer Org we have 508 Testclasses and a lot more normal classes.

Here is the debug log with the latest run:

Command:
mvn compile exec:java -Dexec.mainClass="com.sforce.cd.apexUnit.ApexUnitRunner" -Dexec.args="-org.login.url XX -org.username XX -org.password XX -org.client.id XX -org.client.secret XX -regex.for.selecting.test.classes.to.execute * -regex.for.selecting.source.classes.for.code.coverage.computation *"


CLI:
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.ApexUnitRunner - ####################################   Processing the Apex test classes specified by the user  #################################### 
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.utils.ApexClassFetcherUtils - Using regex(es): * to fetch apex classes
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.utils.ApexClassFetcherUtils - Using regex: "*" to fetch apex classes
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.connection.ConnectionHandler - Bulk connection established.
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.testEngine.AsyncBulkApiHandler - Creating batch for the test classes to execute using bulk connection....
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] ERROR com.sforce.cd.apexUnit.ApexUnitUtils - Error while fetching results for the batch jobFIELD_INTEGRITY_EXCEPTION:Class ID: id value of incorrect type: 01qL00000000oQYIAY:ApexClassId --
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.ApexUnitUtils - Shutting down ApexUnit
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1329)
	at com.sforce.cd.apexUnit.ApexUnitUtils.shutDownWithErrMsg(ApexUnitUtils.java:68)
	at com.sforce.cd.apexUnit.client.testEngine.AsyncBulkApiHandler.checkResults(AsyncBulkApiHandler.java:295)
	at com.sforce.cd.apexUnit.client.testEngine.AsyncBulkApiHandler.handleBulkApiFlow(AsyncBulkApiHandler.java:100)
	at com.sforce.cd.apexUnit.client.testEngine.TestExecutor.testExecutionFlow(TestExecutor.java:61)
	at com.sforce.cd.apexUnit.ApexUnitRunner.main(ApexUnitRunner.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)

**Comment by 13Rise** [comment] 2015-12-08 23:00
we want to use your tool for our continuous integration process.
In this process we want to run testdeployments, realdeployments, static code analysis with Sonar Qube and testclass runs with code coverage report.
Our missing part is only the testclass execution with code coverage report.

On the customer Org we have 508 Testclasses and a lot more normal classes.

Here is the debug log with the latest run:

Command:
mvn compile exec:java -Dexec.mainClass="com.sforce.cd.apexUnit.ApexUnitRunner" -Dexec.args="-org.login.url XX -org.username XX -org.password XX -org.client.id XX -org.client.secret XX -regex.for.selecting.test.classes.to.execute * -regex.for.selecting.source.classes.for.code.coverage.computation *"


CLI:
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.ApexUnitRunner - ####################################   Processing the Apex test classes specified by the user  #################################### 
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.utils.ApexClassFetcherUtils - Using regex(es): * to fetch apex classes
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.utils.ApexClassFetcherUtils - Using regex: "*" to fetch apex classes
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.connection.ConnectionHandler - Bulk connection established.
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.testEngine.AsyncBulkApiHandler - Creating batch for the test classes to execute using bulk connection....
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] ERROR com.sforce.cd.apexUnit.ApexUnitUtils - Error while fetching results for the batch jobFIELD_INTEGRITY_EXCEPTION:Class ID: id value of incorrect type: 01qL00000000oQYIAY:ApexClassId --
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.ApexUnitUtils - Shutting down ApexUnit
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1329)
	at com.sforce.cd.apexUnit.ApexUnitUtils.shutDownWithErrMsg(ApexUnitUtils.java:68)
	at com.sforce.cd.apexUnit.client.testEngine.AsyncBulkApiHandler.checkResults(AsyncBulkApiHandler.java:295)
	at com.sforce.cd.apexUnit.client.testEngine.AsyncBulkApiHandler.handleBulkApiFlow(AsyncBulkApiHandler.java:100)
	at com.sforce.cd.apexUnit.client.testEngine.TestExecutor.testExecutionFlow(TestExecutor.java:61)
	at com.sforce.cd.apexUnit.ApexUnitRunner.main(ApexUnitRunner.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)

**Comment by 13Rise** [comment] 2015-12-08 23:01
Logback.xml

<configuration>

  <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
    <layout class="ch.qos.logback.classic.PatternLayout">
      <Pattern>%d{HH:mm:ss} %-5level %logger{36} - %msg%n</Pattern>
    </layout>
  </appender>

	<logger name="com.sforce.cd.apexUnit" level="DEBUG"/>

  <root level="DEBUG">
    <appender-ref ref="STDOUT" />
  </root>

</configuration>

**Comment by pmedapuram** [comment] 2016-02-01 23:08
@13Rise  Going through the community forums, this looks like an error in the Class ID type. Is this still an error?

If you think there is no Class ID type issue, I would like to reproduce this problem. 

I am also thinking of ways to add better error reporting to the tool to show the test class that is having this problem. Let me know your thoughts.

**Comment by leboff** [comment] 2016-02-03 22:35
@pmedapuram the issue is that the fetchApexClassesBasedOnRegex would retrieve both ApexClasses and ApexTriggers if you supplied the "*" wild card and I'm assuming try to execute the triggers as tests (the id from the error message starts with "01q" so its a trigger as opposed to "01p" for classes).  Hopefully this pull request should resolve it #24

**Comment by 13Rise** [comment] 2016-02-04 09:18
Hi Bryan,

that make sense, i will try if the branch is merged.

bye
marian

2016-02-03 23:36 GMT+01:00 Bryan Leboff <notifications@github.com>:

**Comment by adarsh-ramakrishna-sfdc** [comment] 2016-03-09 00:40
PR #24 has been merged which resolves this issue. Closing the issue as fixed.

**Closed by adarsh-ramakrishna-sfdc** 2016-03-09 00:40 UTC
Labels: bug
