### ISSUE TITLE
ApexUnit is unable to distinguish test class names by their namespace.

### ISSUE THREAD

**Issue by tfuda** [forcedotcom/ApexUnit#10] opened 2015-11-23 15:39 UTC
We've got a rather large code-base with about 100 test classes. This code is part of a managed package. The code also depends on other managed packages, with their own package namespace. So, our development environments contain both un-namespaced Apex test classes that are part of the package we're developing, plus namespaced test classes that are part of managed packages that are installed in the developer org. In some cases, the test class names collide across packages. For example, the installed package with the namespace "PackageA" contains a test class called Test_CustomQualification, and the package under development also contains a test class called Test_CustomQualification. If I create a test class manifest that contains Test_CustomQualification, ApexUnit seems to be unable to distinguish the two identically named test classes, and occasionally runs PackageA.Test_CustomQualification instead of the un-namespaced class that I intended to run.

**Comment by tfuda** [comment] 2015-11-23 17:15
I'm thinking that one possible way to solve this would be to add a command line option that would allow you to specify a comma separated list of package namespaces to exclude. So, in my scenario, I would exclude "PackageA" test classes during execution.

**Comment by adarsh-ramakrishna-sfdc** [comment] 2015-12-09 19:36
Hi @tfuda ,
Thanks for reaching out. We will look into the issue. Currently the tool picks up only one test class and namespace was not considered. We will look to make changes to facilitate this request.

Thanks,
Adarsh

**Comment by vamshi-sfdc** [comment] 2015-12-09 22:18
This is an enhancement request that was not under the initial scope

**Comment by tfuda** [comment] 2015-12-10 12:18
Perhaps a more simple solution would be to confine the tests to those test classes in the org's default namespace. Right now it appears that the code does something like this [SELECT * FROM ApexClass WHERE Name = :nameFromManifest], without considering ApexClass.NamespacePrefix. It seems to me that the most common use case for ApexUnit is to run your local unit tests (those in the org's default namespace, which may, or may not be blank). Typically you aren't concerned with running test classes that are part of installed managed packages. The complicating factor with this approach is that I don't know of a reliable to determine the org's default namespace without first querying the ApexClass table to retrieve the NamespacePrefix of a class that you KNOW will exist in the default namespace of the org. I'll do a bit of digging to see if I can come up with a better way of determining the default namespace that doesn't require any carnal knowledge of the Apex classes in the org.

**Comment by pmedapuram** [comment] 2016-01-22 18:40
The issue is resolved in https://github.com/forcedotcom/ApexUnit/pull/18
All classes by default are resolved to the default namespace.

**Closed by pmedapuram** 2016-01-22 18:40 UTC
Labels: bug
